version: "3"
services:
  database:
    image: "postgres:11"
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - config.env
    volumes:
      - ./data:/var/lib/postgresql/data
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    mem_limit: 1024m
    mem_reservation: 512m
    cpus: 1
    restart: unless-stopped
